  set_unless[:repo][:default][:repository] = ""
  set_unless[:repo][:default][:revision] = ""
  set_unless[:repo][:default][:provider_type] = ""
  set_unless[:repo][:svn][:svn_username] = ""
  set_unless[:repo][:svn][:svn_password] = ""
  set_unless[:repo][:git][:ssh_key] = ""